    surfaceScalarField muEff
    (
        "muEff",
        twoPhaseProperties.muf()
      + fvc::interpolate(rho*turbulence->nut())
    );

    volScalarField muEffC
    (
        "muEffC",
        twoPhaseProperties.mu()
      + rho*turbulence->nut()
    );


    fvVectorMatrix UEqn
    (
        fvm::ddt(rho, U)
      + fvm::div(rhoPhi, U)
      - fvm::laplacian(muEff, U)
      - (fvc::grad(U) & fvc::grad(muEff))
    //- fvc::div(muEff*(fvc::interpolate(dev(fvc::grad(U))) & mesh.Sf()))
    //  additional term because velocity field is not divergence-free
	  - muEffC*fvc::grad(fvc::div(U)) 
    );

    UEqn.relax();

    if (momentumPredictor)
    {
        solve
        (
            UEqn
         ==
            fvc::reconstruct
            (
                (
//                  fvc::interpolate(interface.sigmaK())*fvc::snGrad(alpha1)
                    fvc::interpolate(sigmaK)*fvc::snGrad(alpha1)
                  - ghf*fvc::snGrad(rho)
                  - fvc::snGrad(p_rgh)
                ) * mesh.magSf()
            )
        );
    }
